### PR TITLE
[Feature] Add Variable Playback Rate

### PR DESCRIPTION
**Pull request by JSKitty**
Adds the necessary UI and hooks to dynamically edit the playback rate, with a safe min/max and Desktop + Mobile support.

## **Unset / Default:**
image

## **Set to 10:**
image

## **Set to a weird value:**
image

### CODE REVIEW

**Comment by JSKitty** [comment]
To test before merging, feel free to use my Instance:
http://173.249.9.77:6969/watch?v=4J0xFUyz1nw

Yes I watched the entire Helluva Boss episode making this.

**Comment by AndromedaCLI** [comment]
Hows the useability on mobile? Is the box scrollable?

**Comment by JSKitty** [comment]
On mobile, just long-press the playback rate button, and the input to add a custom rate will appear.

**Comment by JSKitty** [comment]
And yep, the full rate list is already scrollable, no change here.

**Comment by AndromedaCLI** [comment]
great

**Pull request merged**
